# Generated by Django 5.0.7 on 2024-08-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_friendrequests_userprofile_friend_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friend_requests',
        ),
    ]
